### ISSUE TITLE
Add a body attribute in the span

### ISSUE THREAD

**Issue by AntoineValente** [gas-buddy/opentelemetry-instrumentation-fetch-node#12]
Hey,

Thank you for this instrumentation 🙏
I noticed that the body attribute is missing in the trace. Is there a specific reason for not implementing it?
If you think it's relevant, I can create a PR for it.

Thanks

**Comment by djMax** [comment]
What do you mean by that? Body length or something? I have no problem with a PR for that.

**Comment by AntoineValente** [comment]
Hey, I mean adding the content of the body in the `attributes` of the `span`:  https://github.com/gas-buddy/opentelemetry-instrumentation-fetch-node/blob/main/src/index.ts#L167  

For instance in a `POST` or `PUT` request, it's hard to get the context without having the body.  

While it might not apply to all content types, it's a simple implementation for basic text formats like JSON and can be super handy.

**Comment by djMax** [comment]
This is not what opentelemetry instrumentations are for. It would be a security issue (body often holds personal data), cause the number of metrics to grow without bound, and put a lot of data into Prometheus or whatever upstream store was in use. The issue you describe is much better addressed with logging

**Comment by AntoineValente** [comment]
That makes sense thanks for the reply 🙏
